// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SideWaffle.Creator
{
    static class Vsix
    {
        public const string Id = "65570079-B9BD-4F44-9108-939AABE6A264";
        public const string Name = "Gregt.SideWaffle.Creator";
        public const string Description = @"Gregt Simplifies project template creation and maintenence.";
        public const string Language = "en-US";
        public const string Version = "1.0.4";
        public const string Author = "Greg Trevellick";
        public const string Tags = "template, dotnet";
    }
}
